# Generated by Django 5.2.5 on 2025-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_alter_customuser_email_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
