# Generated by Django 5.2.5 on 2025-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_tag_project_donation_comment_reply_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.tag"
            ),
        ),
    ]
