# Generated by Django 5.2.5 on 2025-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_project_tags_project_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
