# Generated by Django 5.2.5 on 2025-09-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_project_tags_project_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
