# Generated by Django 5.2.5 on 2025-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
